name: Pull/Merge Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codespace-git-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Run Test
        run: |
          # Test content in exercise 1 folder
          cd 01-codespace-git-actions
          
          # Find all directories in the current directory and store them in an array
          DIRS=($(find . -maxdepth 1 -type d))
          
          # Loop through each directory
          for dir in "${DIRS[@]}"; do
            echo "Directory: $dir"
            ls -lah "$dir"
            echo "---------------------------------"
          done