name: Pull/Merge Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codespace-git-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Run Test
        run: |
          cd 01-codespace-git-actions
          ls -lah
